# 9 추천 시스템

## 9-1 추천 시스템의 개요와 배경

### 추천 시스템의 개요와 배경

### 온라인 스토어의 필수 요소, 추천 시스템

### 추천 시스템의 유형

## 9-2 콘텐츠 기반 필터링 추천 시스템

## 9-3 최근접 이웃 협업 필터링

## 9-4 잠재 요인 협업 필터링

### 잠재 요인 협업 필터링의 이해

### 행렬 분해의 이해

### 확률적 경사 하강법을 이용한 행렬 분해

In [ ]:
import numpy as np

# 원본 행렬 R 생성, 분해 행렬 P와 Q 초기화, 잠재 요인 차원 K는 3으로 설정.
R = np.array([[4 , np.NaN , np.NaN , 2 , np.NaN ],
              [np.NaN, 5 , np.NaN , 3 , 1],
              [np.NaN , np.NaN , 3 , 4 , 4],
              [5,2,1,2,np.NaN]])
num_users , num_items = R.shape
K = 3

# P와 Q 행렬의 크기를 지정하고 정규분포를 가진 임의의 값으로 입력합니다.
np.random.seed(1)
P = np.random.normal(scale = 1./K , size = (num_users , K))
Q = np.random.normal(scale = 1./K , size = (num_items , K))

In [27]:
from sklearn.metrics import mean_squared_error

def get_rmse(R , P , Q, non_zeros):
    error = 0
    # 두 개의 분해된 행렬 P와 Q.T의 내적으로 예측 R행렬 생성
    full_pred_matrix = np.dot(P , Q.T)

    # 식제 R 행렬에서 널이 아닌 값의 위치 인덱스 추출해 실제 R 행렬과 예측 행렬의 RMSE 추출
    x_non_zero_ind = [non_zero[0] for non_zero in non_zeros]
    y_non_zero_ind = [non_zero[1] for non_zero in non_zeros]
    R_non_zeros = R[x_non_zero_ind , y_non_zero_ind]
    full_pred_matrix_non_zeros = full_pred_matrix[x_non_zero_ind , y_non_zero_ind]
    mse = mean_squared_error(R_non_zeros , full_pred_matrix_non_zeros)
    rmse = np.sqrt(mse)

    return rmse

In [ ]:
# R > 0 인 행 위치 , 열 위치 , 값을 non_zeros 리스트에 저장.
non_zeros = [ (i,j,R[i,j]) for i in range(num_users) for j in range(num_items) if R[i,j] > 0 ]

steps = 1000
learning_rate = 0.01 
r_lambda = 0.01

# SGD 기법으로 P와 Q매트릭스를 계속 업데이트
for step in range(steps):
    for i, j, r in non_zeros:
        # 실제 값과 예측값의 차이인 오류 값 구함
        eij = r - np.dot(P[i , : ] , Q[j , :].T)
        # Regularization을 반영한 SGD 업데이트 공식 적용
        P[i , :] = P[i , :] + learning_rate*(eij * Q[j,:] - r_lambda*P[i,:])
        Q[j , :] = Q[j , :] + learning_rate*(eij * P[i,:] - r_lambda*Q[j,:])

    rmse = get_rmse(R,P,Q,non_zeros)
    if (step % 50) == 0:
        print('### iteration step : ' , step , " emse : " , rmse)

### iteration step :  0  emse :  3.2388050277987723
### iteration step :  50  emse :  0.4876723101369647
### iteration step :  100  emse :  0.15643403848192458
### iteration step :  150  emse :  0.07455141311978064
### iteration step :  200  emse :  0.043252267985793146
### iteration step :  250  emse :  0.029248328780879226
### iteration step :  300  emse :  0.022621116143829507
### iteration step :  350  emse :  0.019493636196525232
### iteration step :  400  emse :  0.018022719092132773
### iteration step :  450  emse :  0.01731968595344283
### iteration step :  500  emse :  0.016973657887570985
### iteration step :  550  emse :  0.01679680459589558
### iteration step :  600  emse :  0.016701322901884634
### iteration step :  650  emse :  0.016644736912476574
### iteration step :  700  emse :  0.016605910068210012
### iteration step :  750  emse :  0.01657420047570488
### iteration step :  800  emse :  0.01654431582921612
### iteration step :  850  emse :  0.016513751774735037
### i

In [ ]:
pred_matrix = np.dot(P , Q.T)
print('예측 행렬:\n', np.round(pred_matrix , 3))

예측 행렬:
 [[3.991 0.897 1.306 2.002 1.663]
 [6.696 4.978 0.979 2.981 1.003]
 [6.677 0.391 2.987 3.977 3.986]
 [4.968 2.005 1.006 2.017 1.14 ]]


## 9-5 콘텐츠 기반 필터링 실습 - TMDB 5000 영화 데이터 세트

### 장르 속성을 이용한 영화 콘텐츠 기반 필터링

### 데이터 로딩 및 가공

In [6]:
%cd /content/drive/MyDrive/AI/파이썬 머신러닝 완벽가이드/data_sets/archive (2)

/content/drive/MyDrive/AI/파이썬 머신러닝 완벽가이드/data_sets/archive (2)


In [7]:
import pandas as pd
import numpy as np
import warnings; warnings.filterwarnings('ignore')

movies = pd.read_csv('tmdb_5000_movies.csv')
print(movies.shape)
movies.head(1)

(4803, 20)


budget  ... vote_count
0  237000000  ...      11800

[1 rows x 20 columns]

In [8]:
movies_df = movies[['id' , 'title' , 'genres' , 'vote_average' , 'vote_count' , 'popularity' , 'keywords' , 'overview']]

In [9]:
pd.set_option('max_colwidth' , 100)
movies_df[['genres' , 'keywords']][:1]

genres                                                                                             keywords
0  [{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {...  [{"id": 1463, "name": "culture clash"}, {"id": 2964, "name": "future"}, {"id": 3386, "name": "sp...

In [10]:
from ast import literal_eval
movies_df['genres'] = movies_df['genres'].apply(literal_eval)
movies_df['keywords'] = movies_df['keywords'].apply(literal_eval)

In [11]:
movies_df['genres'] = movies_df['genres'].apply(lambda x : [ y['name'] for y in x ])
movies_df['keywords'] = movies_df['keywords'].apply(lambda x : [ y['name'] for y in x])
movies_df[['genres' , 'keywords']][:1]

genres                                                                                             keywords
0  [Action, Adventure, Fantasy, Science Fiction]  [culture clash, future, space war, space colony, society, space travel, futuristic, romance, spa...

### 장르 콘텐츠 유사도 측정

In [12]:
from sklearn.feature_extraction.text import CountVectorizer

# CountVectorizer를 적용하기 위해 공백문자로 word 단위가 구분되는 문자열로 변환.
movies_df['genres_literal'] = movies_df['genres'].apply(lambda x : (' ').join(x) )
count_vect = CountVectorizer(min_df=0 , ngram_range=(1,2))
genre_mat = count_vect.fit_transform(movies_df['genres_literal'])
print(genre_mat.shape)

(4803, 276)


In [14]:
from sklearn.metrics.pairwise import cosine_similarity

genre_sim = cosine_similarity(genre_mat , genre_mat)
print(genre_sim.shape)
print(genre_sim[:1])

(4803, 4803)
[[1.         0.59628479 0.4472136  ... 0.         0.         0.        ]]


In [16]:
genre_sim_sorted_ind = genre_sim.argsort()[ : , ::-1]
print(genre_sim_sorted_ind[:1])

[[   0 3494  813 ... 3038 3037 2401]]


### 장르 콘텐츠 필터링을 이용한 영화 추천

In [17]:
def find_sim_movie(df , sorted_ind , title_name , top_n=10):

    # 인자로 입력된 movies_df DataFrame에서 'title' 칼럼이 입력된 title_name 값인 DataFrame 추출
    title_movie = df[df['title'] == title_name]

    # title_named을 가진 DataFrame의 index 객체를 ndarray로 반환하고
    # sorted_ind 인자로 입력된 genre_sim_sorted_ind 객체에서 유사도 순으로 top_n개의 index 추출
    title_index = title_movie.index.values
    similar_indexes = sorted_ind[title_index , :(top_n)]
    
    # 추출돤 top_n index 출력. top_n index는 2차원 데이터임.
    # dataframe에서 index로 사용하기 위해서 1차원 array로 변경
    print(similar_indexes)
    similar_indexes = similar_indexes.reshape(-1)

    return df.iloc[similar_indexes]

In [18]:
similar_movies = find_sim_movie(movies_df , genre_sim_sorted_ind, 'The Godfather' , 10)
similar_movies[['title' , 'vote_average']]

[[2731 1243 3636 1946 2640 4065 1847 4217  883 3866]]


title  vote_average
2731                          The Godfather: Part II           8.3
1243                                    Mean Streets           7.2
3636                                   Light Sleeper           5.7
1946  The Bad Lieutenant: Port of Call - New Orleans           6.0
2640         Things to Do in Denver When You're Dead           6.7
4065                                      Mi America           0.0
1847                                      GoodFellas           8.2
4217                                            Kids           6.8
883                              Catch Me If You Can           7.7
3866                                     City of God           8.1

In [20]:
movies_df[['title' , 'vote_average' , 'vote_count']].sort_values('vote_average' , ascending = False)[:10]

title  vote_average  vote_count
3519          Stiff Upper Lips          10.0           1
4247     Me You and Five Bucks          10.0           2
4045     Dancer, Texas Pop. 81          10.0           1
4662            Little Big Top          10.0           1
3992                 Sardaarji           9.5           2
2386            One Man's Hero           9.3           2
2970        There Goes My Baby           8.5           2
1881  The Shawshank Redemption           8.5        8205
2796     The Prisoner of Zenda           8.4          11
3337             The Godfather           8.4        5893

In [26]:
C = movies_df['vote_average'].mean()
m = movies_df['vote_count'].quantile(0.6)
print('C:' , round(C,3) , 'm:' , round(m,3))

C: 6.092 m: 370.2


In [27]:
percentile = 0.6
m = movies_df['vote_count'].quantile(percentile)
C = movies_df['vote_average'].mean()

def weighted_vote_average(record):
    v = record['vote_count']
    R = record['vote_average']

    return ( (v/(v+m) * R) + ( (m/(m+v)) * C) )

movies_df['weighted_vote'] = movies_df.apply(weighted_vote_average , axis = 1)

In [28]:
movies_df[['title' , 'vote_average' , 'weighted_vote' , 'vote_count']].sort_values('weighted_vote' , ascending=False)[:10]

title  vote_average  weighted_vote  vote_count
1881  The Shawshank Redemption           8.5       8.396052        8205
3337             The Godfather           8.4       8.263591        5893
662                 Fight Club           8.3       8.216455        9413
3232              Pulp Fiction           8.3       8.207102        8428
65             The Dark Knight           8.2       8.136930       12002
1818          Schindler's List           8.3       8.126069        4329
3865                  Whiplash           8.3       8.123248        4254
809               Forrest Gump           8.2       8.105954        7927
2294             Spirited Away           8.3       8.105867        3840
2731    The Godfather: Part II           8.3       8.079586        3338

In [29]:
def find_sim_movie(df , sorted_ind , title_name , top_n = 10):
    title_movie = df[df['title'] == title_name]
    title_index = title_movie.index.values

    # top_n의 2배에 해당하는 장르 유사성이 높은 인덱스 추출
    similar_indexes = sorted_ind[title_index , :(top_n * 2)]
    similar_indexes = similar_indexes.reshape(-1)
    # 기준 영화 인덱스는 제외
    similar_indexes = similar_indexes[similar_indexes != title_index]

    # top_n의 2배에 해당하는 후보군에서 weighted_vote가 높은 순으로 top_n만큼 추출
    return df.iloc[similar_indexes].sort_values('weighted_vote' , ascending = False)[:top_n]

similar_movies = find_sim_movie(movies_df , genre_sim_sorted_ind , 'The Godfather' , 10)
similar_movies[['title' , 'vote_average' , 'weighted_vote']]

title  vote_average  weighted_vote
2731       The Godfather: Part II           8.3       8.079586
1847                   GoodFellas           8.2       7.976937
3866                  City of God           8.1       7.759693
1663  Once Upon a Time in America           8.2       7.657811
883           Catch Me If You Can           7.7       7.557097
281             American Gangster           7.4       7.141396
4041              This Is England           7.4       6.739664
1149              American Hustle           6.8       6.717525
1243                 Mean Streets           7.2       6.626569
2839                     Rounders           6.9       6.530427

## 9-6 아이템 기반 최근접 이웃 협업 필터링 실습

In [1]:
%cd /content/drive/MyDrive/AI/파이썬 머신러닝 완벽가이드/data_sets/movielens

/content/drive/MyDrive/AI/파이썬 머신러닝 완벽가이드/data_sets/movielens


### 데이터 가공 및 변환

In [3]:
import pandas as pd
import numpy as np

movies = pd.read_csv('movies.csv')
ratings = pd.read_csv('ratings.csv')
print(movies.shape)
print(ratings.shape)

(9125, 3)
(100004, 4)


In [4]:
ratings = ratings[['userId' , 'movieId' , 'rating']]
ratings_matrix = ratings.pivot_table('rating' , index = 'userId' , columns='movieId')
ratings_matrix.head(3)

movieId  1       2       3       4       ...  162376  162542  162672  163949
userId                                   ...                                
1           NaN     NaN     NaN     NaN  ...     NaN     NaN     NaN     NaN
2           NaN     NaN     NaN     NaN  ...     NaN     NaN     NaN     NaN
3           NaN     NaN     NaN     NaN  ...     NaN     NaN     NaN     NaN

[3 rows x 9066 columns]

In [5]:
# title 칼럼을 얻기 위해 movies와 조인
rating_movies = pd.merge(ratings , movies , on = 'movieId')

#columns = 'title'로 title 칼럼으로 피벗 수행.
ratings_matrix = rating_movies.pivot_table('rating' , index = 'userId' , columns='title') 

#NaN 값을 모두 0으로 변환
ratings_matrix = ratings_matrix.fillna(0)
ratings_matrix.head(3) 

title   "Great Performances" Cats (1998)  ...  İtirazım Var (2014)
userId                                    ...                     
1                                    0.0  ...                  0.0
2                                    0.0  ...                  0.0
3                                    0.0  ...                  0.0

[3 rows x 9064 columns]

### 영화 간 유사도 산출 

In [7]:
ratings_matrix_T =  ratings_matrix.transpose()
ratings_matrix_T.head(3)

userId                                   1    2    3    4    ...  668  669  670  671
title                                                        ...                    
"Great Performances" Cats (1998)         0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0
$9.99 (2008)                             0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0
'Hellboy': The Seeds of Creation (2004)  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0

[3 rows x 671 columns]

In [8]:
from sklearn.metrics.pairwise import cosine_similarity

item_sim = cosine_similarity(ratings_matrix_T , ratings_matrix_T)

# cosine_similarity()로 반환된 넘파이 행렬을 영화명을 매칭해 DataFrame으로 변환
item_sim_df = pd.DataFrame(data=item_sim , index=ratings_matrix.columns , columns=ratings_matrix.columns)

print(item_sim_df.shape)
item_sim_df.head(3)

(9064, 9064)


title                                    "Great Performances" Cats (1998)  ...  İtirazım Var (2014)
title                                                                      ...                     
"Great Performances" Cats (1998)                                      1.0  ...                  0.0
$9.99 (2008)                                                          0.0  ...                  0.0
'Hellboy': The Seeds of Creation (2004)                               0.0  ...                  0.0

[3 rows x 9064 columns]

In [9]:
item_sim_df["Godfather, The (1972)"].sort_values(ascending=False)[:6]

title
Godfather, The (1972)                        1.000000
Godfather: Part II, The (1974)               0.773685
Goodfellas (1990)                            0.620349
One Flew Over the Cuckoo's Nest (1975)       0.568244
American Beauty (1999)                       0.557997
Star Wars: Episode IV - A New Hope (1977)    0.546750
Name: Godfather, The (1972), dtype: float64

In [10]:
item_sim_df["Inception (2010)"].sort_values(ascending=False)[1:6]

title
Dark Knight, The (2008)          0.656999
Avatar (2009)                    0.633687
Dark Knight Rises, The (2012)    0.589308
Inglourious Basterds (2009)      0.580237
District 9 (2009)                0.576054
Name: Inception (2010), dtype: float64

### 아이템 기반 최근접 이웃협업 필터링으로 개인화된 영화 추천

In [11]:
def predict_rating(ratings_arr , item_sim_arr ):
    ratings_pred = ratings_arr.dot(item_sim_arr) / np.array([np.abs(item_sim_arr).sum(axis=1) ] )
    return ratings_pred

In [13]:
ratings_pred = predict_rating(ratings_matrix.values , item_sim_df.values)
ratings_pred_matrix = pd.DataFrame(data=ratings_pred , index=ratings_matrix.index, columns = ratings_matrix.columns)
ratings_pred_matrix.head(3)

title   "Great Performances" Cats (1998)  ...  İtirazım Var (2014)
userId                                    ...                     
1                               0.014679  ...             0.000000
2                               0.034046  ...             0.013151
3                               0.008073  ...             0.048887

[3 rows x 9064 columns]

In [14]:
from sklearn.metrics import mean_squared_error

# 사용자가 평점을 부여한 영화에 대해서만 예측 성능 평가 MSE를 구함.
def get_mse(pred, actual):
    # 평점이 있는 실제 영화만 추출
    pred = pred[actual.nonzero()].flatten()
    actual = actual[actual.nonzero()].flatten()
    return mean_squared_error(pred , actual)

print('아이템 기반 모든 최근접 이웃 MSE: ', get_mse(ratings_pred , ratings_matrix.values ))

아이템 기반 모든 최근접 이웃 MSE:  10.255398119852726


In [15]:
def predict_rating_topsim(ratings_arr , item_sim_arr, n=20):
    # 사용자-아이템 평점 행렬 크기만큼 0으로 채운 예측 행렬 초기화
    pred = np.zeros(ratings_arr.shape)

    # 사용자-아이템 평점 행렬의 열 크기만큼 루프 수행.
    for col in range(ratings_arr.shape[1]):
        # 유사도 행렬에서 유사도가 큰 순으로 n개 데이터 행렬의 인덱스 반환
        top_n_items = [np.argsort(item_sim_arr[: , col])[:-n-1:-1]]
        # 개인화된 예측 평점을 계산
        for row in range(ratings_arr.shape[0]):
            pred[row , col] = item_sim_arr[col, :] [ top_n_items].dot(ratings_arr[row , :][top_n_items].T)
            pred[row , col] /= np.sum(np.abs(item_sim_arr[col, :] [ top_n_items]))
    
    return pred

In [16]:
ratings_pred = predict_rating_topsim(ratings_matrix.values , item_sim_df.values , n=20)
print('아이템 기반 최근접 TOP-20 이웃 MSE: ' , get_mse(ratings_pred , ratings_matrix.values ))

# 계산된 예측 평점 데이터는 DataFrame으로 재생성
ratings_pred_matrix = pd.DataFrame(data=ratings_pred, index=ratings_matrix.index, columns = ratings_matrix.columns)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:11: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  # This is added back by InteractiveShellApp.init_path()
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:12: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  if sys.path[0] == '':


아이템 기반 최근접 TOP-20 이웃 MSE:  3.9706198358584595


In [17]:
user_rating_id = ratings_matrix.loc[9,:]
user_rating_id[ user_rating_id > 0].sort_values(ascending=False)[:10]

title
As Good as It Gets (1997)                      5.0
Fargo (1996)                                   5.0
William Shakespeare's Romeo + Juliet (1996)    5.0
Shadowlands (1993)                             5.0
Matrix, The (1999)                             5.0
Schindler's List (1993)                        5.0
Dead Man Walking (1995)                        5.0
Truman Show, The (1998)                        5.0
Edward Scissorhands (1990)                     4.0
Ever After: A Cinderella Story (1998)          4.0
Name: 9, dtype: float64

In [20]:
def get_unseen_movies(ratings_matrix , userId):
    # userId로 입력받은 사용자의 모든 영화 정보를 추출해 Series로 반환함
    # 반환된 user_rating은 영화명(title)을 인덱스로 가지는 Series 객체임.
    user_rating = ratings_matrix.loc[userId, :]

    # user_rating이 0보다 크면 기존에 관람한 영화임. 대상 인덱스를 추출해 list 객체로 만듦.
    already_seen = user_rating[ user_rating > 0 ].index.tolist()

    # 모든 영화명을 list객체로 만듦
    movies_list = ratings_matrix.columns.tolist()

    # list comprehension으로 already_seen에 해당하는 영화는 movies_list에서 제외함.
    unseen_list = [movie for movie in movies_list if movie not in already_seen ]

    return unseen_list

In [21]:
def recomm_movie_by_userid(pred_df, userId , unseen_list , top_n = 10):
    # 예측 평점 DataFram에서 사용자 id 인덱스와 unseen_list로 들어온 영화명 칼럼을 추출해
    # 가장 예측 평점이 높은 순으로 정렬함.
    recomm_movies = pred_df.loc[userId , unseen_list].sort_values(ascending=False)[:top_n]
    return recomm_movies

# 사용자가 관람하지 않는 영화명 추출
unseen_list = get_unseen_movies(ratings_matrix, 9)

# 아이템 기반의 최근접 이웃 협업 필터링으로 영화 추천
recomm_movies = recomm_movie_by_userid(ratings_pred_matrix , 9 ,unseen_list , top_n = 10)

# 평점 데이터를 DataFrame으로 생성,
recomm_movies = pd.DataFrame(data = recomm_movies.values , index=recomm_movies.index , columns=['pred_score'])

recomm_movies

pred_score
title                                  
American Beauty (1999)         1.258391
Pulp Fiction (1994)            1.075948
Usual Suspects, The (1995)     1.063974
Jerry Maguire (1996)           1.047494
English Patient, The (1996)    1.028489
Forrest Gump (1994)            1.021220
Piano, The (1993)              1.008307
L.A. Confidential (1997)       0.992033
Rain Man (1988)                0.976421
Braveheart (1995)              0.918724

## 9-7 행렬 분해를 이용한 잠재 요인 협업 필터링 실습

In [22]:
def matrix_factorization(R , K , steps = 200 , learning_rate = 0.01 , r_lambda = 0.01):
    num_users , num_items = R.shape
    # P와 Q 매트릭스의 크기를 지정하고 정규 분포를 가진 랜덤한 값을 입력합니다.
    np.random.seed(1)
    P = np.random.normal(scale=1./K , size= (num_users , K))
    Q = np.random.normal(scale=1./K , size= (num_items , K))

    prev_rmse = 10000
    break_count = 0

    # R > 0 인 행 위치 , 열 위치 , 값을 non_zeros 리스트 객체에 저장.
    non_zeros = [ (i , j, R[i, j]) for i in range(num_users) for j in range(num_items) if R[i , j] > 0]

    # SGC기법으로 P와 Q 매트릭스를 계속 업데이트
    for step in range(steps):
        for i, j , r in non_zeros:
            # 실제 값과 예측 값의 차이인 오류 값 구함.
            eij = r - np.dot(P[i,:] , Q[j,:].T )
            # Regularization을 반영한 SGD업데이트 공식 적용
            P[i,:] = P[i , :] + learning_rate * (eij * Q[j , :] - r_lambda*P[i,:])
            Q[j, :] = Q[j,:] +  learning_rate * (eij * P[i , :] - r_lambda*Q[j,:])

        rmse = get_rmse(R,P,Q,non_zeros)
        if (step % 10) == 0:
            print("### iteration step : ", step , " rmse : ", rmse)

    return P, Q

In [24]:
import pandas as pd
import numpy as np

movies = pd.read_csv('movies.csv')
ratings = pd.read_csv('ratings.csv')
ratings = ratings[['userId' , 'movieId', 'rating']]
ratings_matrix = ratings.pivot_table('rating' , index='userId' , columns='movieId')

# title 칼럼을 얻기 위해 movies와 조인 수행.
rating_movies = pd.merge(ratings , movies , on = 'movieId')
# columns='title' 로 title 칼럼으로 pivot 수행.
ratings_matrix = rating_movies.pivot_table('rating' , index='userId' , columns='title')

In [28]:
P ,Q = matrix_factorization(ratings_matrix.values , K=50 , steps=100 , learning_rate =0.01, r_lambda = 0.01 )
pred_matrix = np.dot(P, Q.T)

### iteration step :  0  rmse :  2.9320565818473825
### iteration step :  10  rmse :  0.7499900285865972
### iteration step :  20  rmse :  0.5275349643538034
### iteration step :  30  rmse :  0.38354378256464045
### iteration step :  40  rmse :  0.3017115996487719
### iteration step :  50  rmse :  0.2547302025929975
### iteration step :  60  rmse :  0.22614838269743007
### iteration step :  70  rmse :  0.20743903539394296
### iteration step :  80  rmse :  0.19434445700230893
### iteration step :  90  rmse :  0.18468747401810467


In [29]:
ratings_pred_matrix = pd.DataFrame(data=pred_matrix , index = ratings_matrix.index , columns = ratings_matrix.columns)
ratings_pred_matrix.head(3)

title   "Great Performances" Cats (1998)  ...  İtirazım Var (2014)
userId                                    ...                     
1                               1.745341  ...             2.139596
2                               2.162452  ...             2.845496
3                               2.250018  ...             2.857210

[3 rows x 9064 columns]

In [31]:
# 사용자가 관람하지 않은 영화명 추출
unseen_list = get_unseen_movies(ratings_matrix , 9)

# 잠재 요인 협업 필터링으로 영화 추천
recomm_movies = recomm_movie_by_userid(ratings_pred_matrix , 9 , unseen_list , top_n = 10)

# 평점 데이터를 DataFrame으로 생성,
recomm_movies = pd.DataFrame(data=recomm_movies.values , index = recomm_movies.index)
columns=['pred_score']
recomm_movies

0
title                                                       
Lives of Others, The (Das leben der Anderen) (2...  5.342580
Bowling for Columbine (2002)                        5.189271
Boys Don't Cry (1999)                               5.084508
WALL·E (2008)                                       5.059675
Run Lola Run (Lola rennt) (1998)                    5.047097
Big Lebowski, The (1998)                            5.046238
Finding Nemo (2003)                                 5.045660
Amelie (Fabuleux destin d'Amélie Poulain, Le) (...  5.009302
Dancer in the Dark (2000)                           4.960101
In the Line of Fire (1993)                          4.953395

## 9-8 파이썬 추천 시스템 패키지 - Surprise

In [32]:
from surprise import SVD

ModuleNotFoundError: ignored